### ISSUE TITLE
How its work?

### ISSUE THREAD

**Issue by TomKein** [noiach/vite-plugin-graphql-loader#1]
I have a file: test.gql
`query GetAuthState {  authState }`
I have an import: 
`import { GetAuthState } from './graphql-operations/test.gql'`
And its produce this error:
Uncaught SyntaxError: The requested module '/src/graphql-operations/test.gql?t=1676882148580&import' does not provide an export named 'GetAuthState' (at apollo-client.js?t=1676882156504:7:10)
Whats wrong?
P.S. SandBox to reproduce: https://codesandbox.io/p/sandbox/rough-dream-2jsm9q?selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A9%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A9%7D%5D

**Comment by TomKein** [comment]
I think its configuration problem. Its should be investigated.
Can you also add to project section 'Example' with minimal full featured solution.
Thx!

**Comment by emahuni** [comment]
I am running into this same issue. I have realised that vite is assuming that the env is esm and not commonjs. So this package is creating a commonjs virtual package. Can't this be changed to just generate esm modules instead, where it generates `module.exports = doc` and `module.exports['...'] = ...` to `export default doc` and `export const '...' = ...` making it an esm module. 

However, it should be interesting to see the actual configuration that makes this work with vite without doing this as @TomKein suggested.

**Comment by noiach** [comment]
@TomKein if you still working on this, try version `2.0.0` which includes @emahuni's fixes.

If you are using TypeScript also include a file in your project called `graphql.d.ts`:

```
declare module "*.gql" {
    const Query: import("graphql").DocumentNode;
    export default Query;
}
// Or `declare module "*.gql";` to be able to export fragments
```

and change your import from

```
import { GetAuthState } from './graphql-operations/test.gql'
```

 to

```
  import GetAuthState from './graphql-operations/test.gql'
  ```

I've added these instructions to the README.
